channels:
  - plotly
  - nvidia
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - jupyterlab
  - notebook
  - ipywidgets
  - jupyterlab_widgets
  - matplotlib
  - seaborn
  - plotly
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - tensorboard